nome = input ('Qual seu nome disgraça?')
ano = input ('Que ano você nasceu vagabundagem?')
mês = input ('Que mês tu surgiu pra esse mundo?')
dia = input ('Que dia tua mãe te pariu?')
hora = input ('Em que horas você nasceu?')
print ('=====================================')
print ('=', nome, 'nasceu: ' , dia, '/' , mês, '/' , ano,'==')
print ('=ÁS: ' , hora, '                       ==')
print ('=====================================')
